### ISSUE TITLE
[Feature Request] Add system profiles as trigger for fingerprint on/off

### ISSUE THREAD

**Issue by beerisgood** [linux-colonel/AdminControl#3]
It would be nice if you can include the system profiles (dont know if other roms support it, but LineageOS does) as trigger to enable or disable fingerprint unlock.
So for example if system profile "home" is activ, a fast unlock with fingerprint is possible, but not if profile "outside" is active

**Comment by linux-colonel** [comment]
Yeah I was thinking the same thing.

**Comment by beerisgood** [comment]
How is the status?

**Comment by beerisgood** [comment]
*Push*

**Comment by beerisgood** [comment]
*push*

**Comment by crispyduck00** [comment]
Would be a great feature!
