### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by ghost** [linux-colonel/AdminControl#5]

**Comment by linux-colonel** [comment]
Thanks!  So long as the licensing is copyleft I'd be glad to have a new logo.  Feel free to make a pull request.

**Comment by waqasanwar94** [comment]
![2](https://user-images.githubusercontent.com/38813945/40070556-dc2d773c-5887-11e8-8310-1e857b817e56.jpg)

Hello sir 
i make some logos please have a look and let me know if you like anyone from these if you want any changes you can ask me 
Thank you
